### ISSUE TITLE
Exhibit A in LICENSE

### ISSUE THREAD

**Issue by xCounsel** [Backbase/bb-fuel#7]
Hi guys,

I saw your [license file](https://github.com/Backbase/bb-fuel/blob/master/LICENSE) and have one question to you. Its text ends as "[Exhibit A– THIRD PARTY COMPONENTS]", but there is no data in this exhibit.

If it is empty, why do you specify this exhibit as existing?

Thanks for explanations.

**Comment by richard-blank** [comment]
Thank you for noticing. The third party components have been included in the [license file](https://github.com/Backbase/bb-fuel/blob/master/LICENSE) now
